name: rlbench
task_type: single_dataset
task_modes: []

shape_meta: &shape_meta
  image_resolution: 256
  action:
    shape:
    - 10
  obs:
    agentview_rgb:
      shape:
      - 3
      - 256
      - 256
      type: rgb
    language:
      shape:
      - 15

shape_meta_env: &shape_meta_env
  image_resolution: 256
  action:
    shape:
    - 10
  obs:
    agentview_image:
      shape:
      - 3
      - 256
      - 256
      type: rgb
      
dataset:
  _target_: unified_video_action.dataset.rlbench_dataset.RLBenchDataset
  shape_meta: *shape_meta
  abs_action: true
  dataset_path: data/rlbench
  language_emb_model: clip
  horizon: 32
  n_obs_steps: 16
  pad_after: 7
  pad_before: 1
  rotation_rep: rotation_6d
  seed: 42
  use_cache: true
  val_ratio: 0.02
  data_aug: true
  normalizer_type: all

